# (c) 2016 DataNexus Inc.  All Rights Reserved
---
# if the `zk_nodes` array is not defined then we're
# performing a single-node deployment and we should configure
# a local kafka-zookeeper service
- block:
  - name: Create kafka-zookeeper service file
    template:
      src: "../templates/{{kafka_distro}}-zookeeper.j2"
      dest: /etc/systemd/system/kafka-zookeeper.service
      mode: 0644
    when: (zk_nodes | default([])) == []
  - name: Create kafka service file
    template:
      src: "../templates/{{kafka_distro}}-kafka.j2"
      dest: /etc/systemd/system/kafka.service
      mode: 0644
  - name: Create confluent-schema-registry service file
    template:
      src: ../templates/confluent-schema-registry.j2
      dest: /etc/systemd/system/confluent-schema-registry.service
      mode: 0644
    when: kafka_distro == "confluent"
  - name: restart systemctl daemon
    command: systemctl daemon-reload
  become: true
